### ISSUE TITLE
Update to latest v2.11.5

### ISSUE THREAD

**Issue by kikyps** [djp952/prebuilt-libxml2#1]
Please can u make perbuilt for latest version of libxml2, i try to build but not successfull. thanks

**Comment by djp952** [comment]
I have abandoned the parent project this needed for "reasons" and am no longer willing to update the required dependencies. So, while I am sorry, the answer is no. IIRC libxml2 became harder to compile than it was in the past, but I have no active need to deal with that any longer. Please consider this as "abandoned" as well; everyone is on their own with it :(
